### PR TITLE
Add support for phx-value-*

### PR DESCRIPTION
**Pull request by miguel-s**
Related to #330.

Discussion about the name of the prop is still open. Options so far are:
- `values`
- `event_values`
- `events_values`

Please let me know if you have any other suggestions and which option you prefer.

### CODE REVIEW

**Comment by harmon25** [comment]
I like just `values` over `event_values` and `events_values`.

`phx_values` would be my more explicit suggestion, if we wanted to go in that direction.

**Comment by msaraiva** [comment]
@miguel-s we'll eventually have to create a related `:values` directive to be able to do the same thing for HTML tags since we don't use attributes to do that in regular HTML nodes, only directives. 

Do you think it would be confusing to users to have both `values` and `:values`? If so, is there any alternative? I can't see any so I believe we'll have to provide both and make sure we document clear enough that `values` is just a custom property defined some of the built-in components (not a general use prop that can be used anywhere) and `:values`, a directive that applies only to HTML elements.

Thoughts?

**Comment by miguel-s** [comment]
@msaraiva for this specific case I think we should go ahead. It mirrors how we handle events currently (e.g. `:on-click` & `click`).

However, the difference between props and directives seems to be of the more common questions for new Surface users. 
For example a common question I see is: Why does `<Button :on-click="foo" />` not work?

**Comment by miguel-s** [comment]
@harmon25 thanks for adding your voice.

In Surface we try to avoid the `phx` prefix, e.g. `phx-click` (LiveView) and `:on-click` (Surface).

**Comment by msaraiva** [comment]
> However, the difference between props and directives seems to be a common question for new Surface users.
> For example a common question I see is: Why does `<Button :on-click="foo" />` not work?

Agreed. We should probably do a better job with the docs.

**Review by msaraiva — APPROVED** [review]

**Review by Malian — APPROVED** [review]

**Pull request merged**
