### PR TITLE
Support Phoenix Live View >= 1.15.6

### PR DESCRIPTION
**Pull request by maennchen**
Fix for #398

### CODE REVIEW

**Comment by Malian** [comment]
@maennchen Thanks for opening this PR.

After discussion, we believe we should support  `15.0 <=  phoenix live view <= 15.6` and `phoenix live view >= 15.7`. The main reason is that if we just start using the new phoenix live view version, a lot of people using older versions will get in trouble and will start open issues.

We could release a `v0.4.1` of Surface that can work for both. By just copying/pasting that code and conditionally passing the socket based on the version would do the trick. Then, on `v0.5.0`, we can simply remove the condition and accept only the new version.

WDYT? If it's ok for you, could you please adapt the PR to take these change into account?

**Comment by maennchen** [comment]
@Malian Sure, I'll have a look.

**Comment by maennchen** [comment]
@Malian Is this acceptable?

**Comment by msaraiva** [comment]
@maennchen thanks! ❤️

**Pull request merged**
