### PR TITLE
updates to liveview 0.20.x

### PR DESCRIPTION
**Pull request by harmon25**
- runs mix deps.update --all
- Improves compatibility with lv 0.20.x (by updating deps)
- ~~updates to latest sorcerer (0.14.0) (which breaks phx.new patcher)~~

Open to suggestions on how to enable the new `debug_heex_annotations` feature, it might have to be re-implemented for surface though?

Please help! @msaraiva 

related: #713

### CODE REVIEW

**Comment by Zurga** [comment]
Is updating to sourceror (0.14.0) necessary for the bump of the LiveView dep? If not, I would suggest leaving that for later.
Can confirm that using an override in my mix.exs there are no problems with LiveView 0.20.0.

**Comment by dougw-bc** [comment]
It is not! 
I ended up reverting that change.

**Comment by harmon25** [comment]
It is not!
Updated the PR, scratching that line.
I ended up reverting back to sorcerer 0.12.0

**Comment by harmon25** [comment]
Hi @msaraiva,
Thanks for taking a look!
I ended up reverting sorcerer back to 0.12.0 after the same discovery, this PR does not include that change - and sorcerer remains at 0.12.0

**Comment by noozo** [comment]
Got an error with LV 0.20 and current surface versions:

```
** (exit) an exception was raised:
    ** (ArgumentError) expected field to be an atom, got: "_persistent_id"
        (phoenix_ecto 4.4.3) lib/phoenix_ecto/html.ex:122: Phoenix.HTML.FormData.Ecto.Changeset.input_value/3
        (phoenix_html 3.3.3) lib/phoenix_html/form.ex:938: Phoenix.HTML.Form.generic_input/4
        (phoenix_html 3.3.3) lib/phoenix_html/form.ex:782: Phoenix.HTML.Form.hidden_inputs_for/3
        (elixir 1.15.4) lib/enum.ex:4317: Enum.flat_map_list/2
        (surface 0.11.1) lib/surface/components/form/hidden_inputs.ex:20: anonymous fn/2 in Surface.Components.Form.HiddenInputs."render (overridable 1)"/1
```

**Comment by noozo** [comment]
Actually it seems to be related to surface 0.11.1 (independently of the LV version), since reverting to 0.11.0 no longer throws that error.

**Comment by harmon25** [comment]
It appears the latest liveview `0.20.2` has introduced some changes that requires a bit of work to align on the surface side.

I started working through the changes here: https://github.com/harmon25/surface/tree/lv-0.20.2 

here is the output from failing tests:

```
Excluding tags: [integration: true]

..........................................................................................................................................................................................................................................................................................................................................................................................................................

  1) test forward props to the underlying live_render call (Surface.LiveView.LiveViewTest)
     test/surface/live_view_test.exs:52
     Assertion with =~ failed
     code:  assert html =~ ~S"<span class=\"lv\""
     left:  "<div id=\"phx-F6JK91E-pco3hTwD\" data-phx-session=\"SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY2Sks5MUUtcGNvM2hUd0R3B3Nlc3Npb250AAAAAHcKcGFyZW50X3BpZHcDbmlsdwR2aWV3dzpFbGl4aXIuU3VyZmFjZS5MaXZlVmlldy5MaXZlVmlld1Rlc3QuTGl2ZVZpZXdXaXRoUHJvcHNWaWV3dwZyb3V0ZXJ3A25pbHcJcm9vdF92aWV3dzpFbGl4aXIuU3VyZmFjZS5MaXZlVmlldy5MaXZlVmlld1Rlc3QuTGl2ZVZpZXdXaXRoUHJvcHNWaWV3dwhyb290X3BpZHcDbmlsdwxsaXZlX3Nlc3Npb253A25pbG4GAOvcEYOMAWIAAVGA.UDo4is3aWa9KlsXwmYLP_ZvN2B_lplcmE9_Qlhoii_Q\" data-phx-static=\"SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY2Sks5MUUtcGNvM2hUd0R3BWZsYXNodAAAAAB3CmFzc2lnbl9uZXdsAAAAAXcLX19jb250ZXh0X19qbgYA69wRg4wBYgABUYA.Dy8sHbOlrB-I8e3HjTLal9SvjUxtyx6uuPb1-7GLk-s\"><span id=\"123\" data-phx-session=\"SFMyNTY.g2gDaAJhBXQAAAAHdwJpZG0AAAADMTIzdwdzZXNzaW9udAAAAAFtAAAAB3VzZXJfaWRtAAAAB1VTRVJfSUR3CnBhcmVudF9waWR3A25pbHcEdmlld3c2RWxpeGlyLlN1cmZhY2UuTGl2ZVZpZXcuTGl2ZVZpZXdUZXN0LkxpdmVWaWV3V2l0aFByb3BzdwZyb3V0ZXJ3A25pbHcJcm9vdF92aWV3dzZFbGl4aXIuU3VyZmFjZS5MaXZlVmlldy5MaXZlVmlld1Rlc3QuTGl2ZVZpZXdXaXRoUHJvcHN3CHJvb3RfcGlkdwNuaWxuBgDu3BGDjAFiAAFRgA.vvXrtiNF4q-kJyUFjHtcMxnP5R8zWaiY8roA1ZN2H_s\" data-phx-static=\"\" data-phx-sticky=\"data-phx-sticky\" class=\"lv\">User id from session: USER_ID\n</span></div>"
     right: "<span class=\"lv\""
     stacktrace:
       test/surface/live_view_test.exs:56: (test)

......................................................................................................................................................................................................................................

  2) test change tracking is disabled for components using the context (Surface.ContextChangeTrackingTest)
     test/surface/integrations/context_change_tracking_test.exs:78
     Assertion failed, no matching message after 100ms
     Showing 2 of 2 messages in the mailbox
     code: assert_receive {:updated, "1"}
     mailbox:
       pattern: {:updated, "1"}
       value:   {
                  #Reference<0.3485695604.818413571.39880>,
                  {200, [{"content-type", "text/html; charset=utf-8"}, {"cache-control", "max-age=0, private, must-revalidate"}], "<div id=\"phx-F6JK96OuJUSQIlbD\" data-phx-session=\"SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY2Sks5Nk91SlVTUUlsYkR3B3Nlc3Npb250AAAAAW0AAAAIdGVzdF9waWRYdw1ub25vZGVAbm9ob3N0AAAI3gAAAAAAAAAAdwpwYXJlbnRfcGlkdwNuaWx3BHZpZXd3LUVsaXhpci5TdXJmYWNlLkNvbnRleHRDaGFuZ2VUcmFja2luZ1Rlc3QuVmlld3cGcm91dGVydwNuaWx3CXJvb3Rfdmlld3ctRWxpeGlyLlN1cmZhY2UuQ29udGV4dENoYW5nZVRyYWNraW5nVGVzdC5WaWV3dwhyb290X3BpZHcDbmlsdwxsaXZlX3Nlc3Npb253A25pbG4GAFPiEYOMAWIAAVGA.uD4IQgw4XZ7Uof78oMyrVGAEOrrgQeKzX5ZkbH542vs\" data-phx-static=\"SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY2Sks5Nk91SlVTUUlsYkR3BWZsYXNodAAAAAB3CmFzc2lnbl9uZXdsAAAAAXcLX19jb250ZXh0X19qbgYAU-IRg4wBYgABUYA.Pd_Vb7zxO6ur82XtNFSKs3pmH_xkEhHtMcM_hwfCD2w\"><div>\n  \n  <div>\n    Count: 0\n    <div>&quot;field value&quot;</div>\n\n<div>%{}</div>\n\n<div>\n      <div>%{}</div>\n\n    </div>\n\n    <div>%{}</div>\n\n  </div>\n\n\n\n</div>\n</div>"}
                }

       pattern: {:updated, "1"}
       value:   {:plug_conn, :sent}
     stacktrace:
       test/surface/integrations/context_change_tracking_test.exs:94: (test)

.................................................................................................................................................................................................................................................................................................................................................................................warning: Phoenix.LiveView.Helpers.live_patch/2 is deprecated. Use <.link> instead
  test/surface/components/live_patch_test.exs:112: Surface.Components.LivePatchTest.actual_content/2

...........warning: Phoenix.LiveView.Helpers.live_redirect/2 is deprecated. Use <.link> instead
  test/surface/components/live_redirect_test.exs:110: Surface.Components.LiveRedirectTest.actual_content/2

.........................................................................................................................................................................................................................................................................................................................................................
Finished in 7.6 seconds (5.7s async, 1.8s sync)
1 doctest, 1368 tests, 2 failures, 2 excluded

Randomized with seed 913905
```

**Pull request merged**
