### PR TITLE
Ensure deps are loaded using on_load

### PR DESCRIPTION
**Pull request by msaraiva**

### CODE REVIEW

**Comment by joshuataylor** [comment]
Hi!

I'm now getting this error https://github.com/surface-ui/surface/issues/544 until I refresh a couple of times.

**Comment by msaraiva** [comment]
Hi @joshuataylor!

I have a few questions to help me out tracking down this problem:

1. What Surface, Phoenix and LV versions are you using?
2. Are you getting any warning like: `could not load component 'X' called by 'Y'`?
3. Is the project you're working on public so I can clone it and try it out?

Thanks!

**Comment by joshuataylor** [comment]
Versions:

phoenix                 1.6.6    1.6.6   Up-to-date           
phoenix_html            3.2.0    3.2.0   Up-to-date           
phoenix_live_view       0.17.7   0.17.7  Up-to-date           
surface                 0.7.2    0.7.2   Up-to-date          

2/ No warning, it shows the same error as the above issue.

3/ No, but I'll get a reproduction repo out now to show the example.

**Comment by joshuataylor** [comment]
(Also, sorry -- If you would like me to move this to an issue instead of this PR, happy to do so :+1:)

**Comment by joshuataylor** [comment]
Here is the reproduction https://github.com/joshuataylor/surface_example , run this as a normal phoenix app, it does not require a database or anything.

**Comment by msaraiva** [comment]
@joshuataylor I just released `v0.7.3` fixing this. Please let me know if you still run into any issue.

Thanks for taking the time to push an example demonstrating the problem! ❤️

**Pull request merged**
