### PR TITLE
Fix dialyzer issue in EExEngine

### LINKED ISSUE #654: dialyzer complains since v0.8.2
Since e8aea39, I'm getting dialyzer errors across my project in the form of

```
lib/my_web/some_file.ex:1:pattern_match
The pattern can never match the type.

Pattern:
false

Type:
true
```

cc @tiagoefmoraes

### PR DESCRIPTION
**Pull request by dvic**
Fixes #654

### CODE REVIEW

**Comment by dvic** [comment]
I also added `generated: true` to the second block, because although my project didn't trigger that part, I think it suffers from the same problem.

**Comment by msaraiva** [comment]
@dvic thanks! ❤️

**Comment by msaraiva** [comment]
Hey @dvic! We're still getting those dialyzer errors even after the PR. We've made some changes that made the problem disappear for us. Can you check if that branch also solves it for you? https://github.com/surface-ui/surface/tree/v0.8

**Comment by janwillemvd** [comment]
@dvic is away this week, that's why I'm responding.

I can confirm that but [our dialyzer issue](https://github.com/surface-ui/surface/issues/654) was gone since ffaef38f874d9e93e4a1bc4bb94f83f009b3be79.

Also, https://github.com/surface-ui/surface/tree/v0.8 doesn't give any dialyzer warnings or errors 💪🏻.

We're still on LV 0.17 with this project.

**Pull request merged**
