### PR TITLE
Move validations to after compile

### PR DESCRIPTION
**Pull request by Malian**
Related to #334

### CODE REVIEW

**Comment by Malian** [comment]
@msaraiva @lnr0626 @miguel-s The goal of this PR is to move validations from `put_assign!` to `__after_compile__`, not to improve the validations themselves. So it means, they are still rooms for improvements like:

- creating an `Surface.Assign` struct.
- Pass `assign` to `validate_opts` and `validate_opt` instead of passing 99% of the attributes.
- reduce the number of pass through the `assigns`
- introduce `__assigns__()` to be consistent with `__props__` and company
- ...

Before going further I would like to have your opinion/advice especially on the following points:

- One test, still not pass :( As a said on Slack, it is due to the `opts` value that is not a keyword list. When we generate the doc, in `__before_compile__` we haven't performed the validations yet and so the documentation generator fails as it assumes that the `opts` is a keyword list. I have no idea how to solve this as we cannot generate the doc in `__after_compile__` and I do not completely understand the impact of keeping some validation before `__after_compile__`.
- I tried to understand the issue with recursive components, #334 and https://elixirforum.com/t/recursive-surface-component/39019, but I am not able to write a minimum example that reproduces the error. Could you help me with this too?

**Comment by msaraiva** [comment]
@Malian having validation before `__after_compile__` is only a problem if the validation assumes a child already exists, i.e. whenever the module being validated needs to access a child's public interface. e.g. `child.__props__()`, `mod.module_info()`, etc. When that happens, since the parent and the child module are the same, the module can't be compiled as it must wait for itself to be compiled to move on, which can never happen. 

Most validations in that situation are probably in the `Surface.Compiler` module, not in `put_assign!`. I believe only `validate_slot_props_bindings!` has that requirement, however, moving all validations to `__after_compile__` ensures any current or future validation can use the public interface of the module. This makes the API much more consistent as we can implement it assuming the module already exists, avoiding a bunch of conditionals like this: https://github.com/surface-ui/surface/blob/197207f2f3e77af8ad9fa73049a54dd69006952b/lib/surface/api.ex#L182-L193

Generating the docs breaks this as it must be done before compilation. So we have two options:

1. Remove the docs generation
2. Leave the minimum necessary to implement it.

If the minimum for `#2` ends up being a lot, I'd say we should consider removing it.

**Comment by Malian** [comment]
I finally decided to move the validation to `validate_opts_ast` like what we do with the `validate_name_ast`. To be consistent, I added a `validate_type_ast` function.

**Review by msaraiva — APPROVED** [review]
❤️

**Comment by Malian** [comment]
Related to #343

**Pull request merged**
