### PR TITLE
Add a bug template

### PR DESCRIPTION
**Pull request by davydog187**
Adds a template for capturing bug reports from user's of Surface.

### CODE REVIEW

**Comment by msaraiva** [comment]
Hey @davydog187!

Thanks for setting this up. 

Should we add a "Your environment" section to inform the versions of Elixir, Phoenix and Surface?

**Comment by davydog187** [comment]
Version of surface, elixir version, LiveView version?

**Comment by davydog187** [comment]
@msaraiva pushed some updates

**Comment by Malian** [comment]
@davydog187 Thanks! LGTM.

A nice improvement we could do in the future is to write in the bug template some pre-checks to help like:
- Did you look at the "common issues" page?
- Are you using the old syntax: `{{ }}` or the new one `{ }`?
- If you upgraded Surface to  >= 0.5.0, did you run the migration? (link to migration guide)
- etc.

No need to do this now.

**Comment by msaraiva** [comment]
@davydog187 thanks! ❤️

**Comment by davydog187** [comment]
Good ideas @Malian!

**Pull request merged**
