### PR TITLE
LiveView 0.20.2+

### PR DESCRIPTION
**Pull request by harmon25**
- updates to lv 0.20.3
- adds `phoenix_html_helpers` for compatibility
- replaces uses of `Phoenix.HTML.Form` with `PhoenixHTMLHelpers.Form`

### CODE REVIEW

**Comment by tiagoefmoraes** [comment]
@harmon25, thanks for the PR, I solved the context and attribute order issue in https://github.com/surface-ui/surface/pull/733, we'll handle the update to `phoenix_html` [4.0.0](https://github.com/phoenixframework/phoenix_html/blob/main/CHANGELOG.md#v400-2023-12-19) and `phoenix_html_helpers` soon.

**Comment by dougw-bc** [comment]
@tiagoefmoraes Thank you!

**Comment by harmon25** [comment]
@tiagoefmoraes Thanks!!

**Comment by petermueller** [comment]
@tiagoefmoraes, @harmon25, let me know if there's any help or testing needed for when resurrecting the `phoenix_html_helpers` changes comes back around for you all, and thank you for your work :)

**Comment by dan-klasson** [comment]
Any progress on supporting `phoenix_html` 4.0.0?

**Pull request closed without merging**
